name: Deploy to Elastic Beanstalk

on:
  push:
    paths:
      - 'Codes/01-elastic-beanstalk-workflow/helloworld_test.js'  # Correct path relative to the repository root
    branches:
      - test  # Change from "main" to "test"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Change directory to Terraform workspace
        run: cd Codes/01-elastic-beanstalk-workflow

      - name: Initialize Terraform
        run: terraform init
        working-directory: Codes/01-elastic-beanstalk-workflow

      - name: Apply Terraform
        run: terraform apply -auto-approve
        working-directory: Codes/01-elastic-beanstalk-workflow
